# Generated by Django 3.2.7 on 2021-11-12 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_accounts_purchase_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='purchase',
        ),
        migrations.AddField(
            model_name='accounts',
            name='total_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
