# Generated by Django 3.2.7 on 2021-11-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211112_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='total_price',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='price',
            new_name='sales_price',
        ),
    ]
