# Generated by Django 3.2.7 on 2021-11-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211112_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='profit_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
