# Generated by Django 3.2.7 on 2021-11-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_accounts_profit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profit_price',
            field=models.IntegerField(null=True),
        ),
    ]
