# Generated by Django 3.2.7 on 2021-11-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_accounts_profit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='sales',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sales'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='purchase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchase'),
        ),
    ]
