# Generated by Django 3.2.7 on 2021-11-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211112_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
