# Generated by Django 3.2.7 on 2021-11-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_purchase_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='number',
        ),
    ]
