# Generated by Django 3.2.7 on 2021-11-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_purchase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchase'),
        ),
    ]
