# Generated by Django 3.2.7 on 2021-11-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_sales_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_price',
            new_name='price_per',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sales_price',
            new_name='price_per',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
