# Generated by Django 3.2.7 on 2021-11-16 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211115_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 6, 10, 43, 99365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_per',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 6, 10, 43, 99365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price_per',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
