# Generated by Django 3.2.7 on 2021-11-16 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20211116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 6, 20, 22, 88225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_per',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 6, 20, 22, 88225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price_per',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
