# Generated by Django 3.2.7 on 2021-11-19 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20211116_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 7, 12, 44, 408753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 7, 12, 44, 424381, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='sales',
            name='customers',
            field=models.ManyToManyField(null=True, to='dashboard.Customer'),
        ),
    ]
