# Generated by Django 3.2.7 on 2021-11-19 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20211119_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customers',
        ),
        migrations.AddField(
            model_name='customer',
            name='sale',
            field=models.ManyToManyField(null=True, to='dashboard.Sales'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 9, 46, 10, 354498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 9, 46, 10, 354498, tzinfo=utc)),
        ),
    ]
