# Generated by Django 3.2.7 on 2021-11-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/avatar.png', upload_to='profile_pics'),
        ),
    ]
